name: xiaomao

services:
  backend:
    build:
      context: /vol2/1000/web/xiaomao/express-project
      dockerfile: Dockerfile

    container_name: xiaomao-backend
    restart: unless-stopped

    env_file:
      - /vol2/1000/web/xiaomao/.env

    ports:
      - "127.0.0.1:1220:3001"

    volumes:
      - /vol2/1000/web/xiaomao/uploads:/app/uploads

    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
