name: xiaomao

services:
  backend:
    build:
      context: ./express-project
      dockerfile: Dockerfile

    container_name: xiaomao-backend
    restart: unless-stopped

    # NAS user xzy:User
    user: "1000:1001"

    env_file:
      - ./.env

    ports:
      - "127.0.0.1:1220:3001"

    volumes:
      - "${XIAOMAO_UPLOAD_DIR:-/vol2/1000/web/data/xiaomao/uploads}:/app/uploads"

    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
